import { Task } from '@prisma/client';
import type { NextPage } from 'next';
import { signIn, signOut } from 'next-auth/react';
import Head from 'next/head';
import { useState } from 'react';

import { Button, Column, Modal } from '../components';
import { useSession } from '../hooks';
import { COLUMN_STATUSES, COLUMN_LABELS } from '../utils/constants';

const Home: NextPage = () => {
  const [modalOpen, setModalOpen] = useState(false);
  const [modalItemData, setModalItemData] = useState<Task | undefined>(
    undefined
  );
  const session = useSession();

  return (
    <>
      <Head>
        <title>T3 Task Board</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-white w-full min-h-screen">
        <header className="p-4">
          <div className="flex flex-col items-end">
            <Button
              variant={session ? 'secondary' : 'primary'}
              onClick={session ? () => signOut() : () => signIn()}
            >
              {session ? 'Sign out' : 'Sign in'}
            </Button>
          </div>
        </header>
        {session?.user && (
          <main className="w-screen overflow-scroll p-4 min-h-screen">
            <section className="max-auto">
              <section className="flex">
                <h1 className="text-3xl font-bold mr-2">Create task </h1>
                <Button variant="round" onClick={() => setModalOpen(true)}>
                  +
                </Button>
              </section>
              <section>
                <div className="flex w-full mt-6">
                  <>
                    {Object.values(COLUMN_STATUSES).map((key, index) => {
                      return (
                        <Column
                          key={index}
                          name={COLUMN_LABELS[key]}
                          status={key}
                          setModalOpen={setModalOpen}
                          setModalItemData={setModalItemData}
                        />
                      );
                    })}
                  </>
                </div>
              </section>
              <section className="mt-80"></section>
            </section>
          </main>
        )}
        {modalOpen && (
          <Modal
            setModalOpen={setModalOpen}
            modalItemData={modalItemData}
            setModalItemData={setModalItemData}
          />
        )}
      </div>
    </>
  );
};

export default Home;
